sensor:
  - platform: template
    id: display_temp
    lambda: |-
      return id(probe_temp).state;
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: temp_value_label
            text:
              format: "%.1f°"
              args: ["x"]

  - platform: template
    id: display_humidity
    lambda: |-
      return id(probe_humidity).state;
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: humidity_value_label
            text:
              format: "%.0f%%"
              args: ["x"]

  - platform: template
    id: display_vpd
    lambda: |-
      return id(probe_vpd).state;
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: vpd_value_label
            text:
              format: "%.2f"
              args: ["x"]