sensor:
  - platform: template
    id: display_temp
    lambda: |-
      return id(probe_temp).state;
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: temp_value_label
            text:
              format: "%.1f°"
              args: ["x"]

  - platform: template
    id: display_humidity
    lambda: |-
      return id(probe_humidity).state;
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: humidity_value_label
            #Fahrenheit
            text: !lambda |-
              static char buf[16];
              float f = (x * 9.0f / 5.0f) + 32.0f;
              snprintf(buf, sizeof(buf), "%.1f°F", f);
              return buf;

            #Celcius
            #text:
              #format: "%.0f%%"
              #args: ["x"]

  - platform: template
    id: display_vpd
    lambda: |-
      return id(probe_vpd).state;
    update_interval: 10s
    on_value:
      then:
        - script.execute: update_vpd_display